### ISSUE TITLE
按照教程配置，结果报错！

### ISSUE THREAD

**Issue by 1134451886** [heiwa9/XYB_AutoSign_Revision#3]
![image](https://user-images.githubusercontent.com/40816004/155492134-cdd58683-4be9-4604-ba10-edf3db3ede2b.png)
报错代码如下：
`{"errorCode":1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python37/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python37/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python37/lib/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python37/lib/python3.7/imp.py\", line 171, in load_source\n    module = _load(spec)\n  File \"Ϗrozen; importlib._bootstrap&gt;\", line 696, in _load\n  File \"Ϗrozen; importlib._bootstrap&gt;\", line 677, in _load_unlocked\n  File \"Ϗrozen; importlib._bootstrap_external&gt;\", line 724, in exec_module\n  File \"Ϗrozen; importlib._bootstrap_external&gt;\", line 860, in get_code\n  File \"Ϗrozen; importlib._bootstrap_external&gt;\", line 791, in source_to_code\n  File \"Ϗrozen; importlib._bootstrap&gt;\", line 219, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 1\n    Skip to content\n          ^\nSyntaxError: invalid syntax","requestId":"2be26d70-447b-4470-ac25-2384180cd0fd","statusCode":443}`

**Comment by 1134451886** [comment]
发现是Python环境版本选错了，换到3.6之后继续报错。
代码如下：
![image](https://user-images.githubusercontent.com/40816004/155495096-94353883-87e3-4f0b-a85a-99f8c768aebe.png)

**Comment by chenglun11** [comment]
把超时改到20s就行了
