### ISSUE TITLE
server酱发送失败，云函数和python本地运行都会失败。

### ISSUE THREAD

**Issue by acbzdm** [heiwa9/XYB_AutoSign_Revision#5]
云函数日志如下
2022-03-10 20:27:08 正在发送通知

ERROR RequestId:0315487c-7768-4fad-9021-c701e85ab7e5 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 346, in main_handler\n    signHandler(user, sence)\n  File \"/var/user/index.py\", line 324, in signHandler\n    sendNoice(userName + '签到成功')\n  File \"/var/user/index.py\", line 239, in sendNoice\n    if config['server_send_key'] == \"\":\nKeyError: 'server_send_key'","statusCode":430}

END RequestId:0315487c-7768-4fad-9021-c701e85ab7e5

Report RequestId:0315487c-7768-4fad-9021-c701e85ab7e5 Duration:2129ms Memory:128MB MemUsage:17.145729MB

**Comment by hdward9** [comment]
将json 文件中的send_key改为 server_send_key
