### ISSUE TITLE
签退失败

### ISSUE THREAD

**Issue by WhoseBugApple** [heiwa9/XYB_AutoSign_Revision#6]
主函数中 sence=1 修改为 sence='1'后, 此时会去执行签退, 但是执行签退失败, 打开校友邦, 发现没有签退选项

**Comment by hdward9** [comment]
说明你不需要签退这个功能，有的学校要求学生签退，有的学校没有要求签退，就不需要签退

**Comment by WhoseBugApple** [comment]
我尝试签到时把clockstatus改成2, 然后在签退时改为1, 这样可以完整正常签退
